version: '2'

services:
  dmall-product-service:
      image: '${DMALL_DOCKER_REGISTRY}/dmall/product-service:${BUILD_NUMBER}'
      ports:
          - "8083:8083"
      external_links:
        - dmall-config-server/dmall-config-server:dmall-config-server
        - dmall-registry-server/dmall-registry-server:dmall-registry-server
    