version: '2'

services:
  dmall-product-service:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: ec2-52-80-144-157.cn-north-1.compute.amazonaws.com.cn:5000/dmall/product-service:$BUILD_NUMBER
    ports:
      - "8084:8084"