version: '2'

services:
  dmall-product-service:
      image: ec2-54-223-92-91.cn-north-1.compute.amazonaws.com.cn:5000/dmall/product-service:$BUILD_NUMBER
      ports:
          - "8083:8083"
      external_links:
        - dmall-config-server/dmall-config-server:dmall-config-server
        - dmall-registry-server/dmall-registry-server:dmall-registry-server
    